### PR TITLE
[Issue-22]: remove i2c-tools dependency

### PR DESCRIPTION
**Pull request by jempatel**

### CODE REVIEW

**Comment by greenbreakfast** [comment]
Can we also adjust the image builder config so that i2c-tools is still included in the firmware?
Technically omega2-base doesn't *depend* on i2c-tools but it's nice to still have it in the firmware.

**Comment by jempatel** [comment]
> Can we also adjust the image builder config so that i2c-tools is still included in the firmware? Technically omega2-base doesn't _depend_ on i2c-tools but it's nice to still have it in the firmware.

We can handle that from image builder profile file

**Comment by greenbreakfast** [comment]
@jempatel great, please make a PR in that repo and we'll merge both in when the latest build system wrapper release is compiled

**Comment by greenbreakfast** [comment]
https://github.com/OnionIoT/openwrt-imagebuilder-wrapper/pull/15 merged 

merging this in as well

thanks!

**Pull request merged**
