### PR TITLE
[Issue-47]: add package omega2-gpio-lookup

### PR DESCRIPTION
**Pull request by jempatel**

### CODE REVIEW

**Comment by greenbreakfast** [comment]
Hi @jempatel, I think instead of making a separate `omega2-gpio-lookup` package, let's just add this script into the `omega2-base` package. That is, install the `gpio-lookup` script along with the other files installed in `omega2-base`.

That's what I meant in my [response in issue #47](https://github.com/OnionIoT/OpenWRT-Packages/issues/47#issuecomment-1481411810) but I should have communicated more clearly.

**Comment by jempatel** [comment]
> Hi @jempatel, I think instead of making a separate `omega2-gpio-lookup` package, let's just add this script into the `omega2-base` package. That is, install the `gpio-lookup` script along with the other files installed in `omega2-base`.
> 
> That's what I meant in my [response in issue #47](https://github.com/OnionIoT/OpenWRT-Packages/issues/47#issuecomment-1481411810) but I should have communicated more clearly.

@greenbreakfast Changes updated.

**Comment by greenbreakfast** [comment]
Thanks! Pls up the release number for omega2-base and add a few lines of to the GPIO section of `technical-doc.md` to document the usage of gpio-lookup

**Comment by jempatel** [comment]
> 
I did not find`technical-doc.md` in the repo,  Is that part of any repo or do you want to create a new file?

**Comment by greenbreakfast** [comment]
It's in the openwrt-22.03 branch of this repo. 
Find it here: https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/technical-doc.md

**Comment by jempatel** [comment]
> It's in the openwrt-22.03 branch of this repo. Find it here: https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/technical-doc.md

Updated.

**Comment by greenbreakfast** [comment]
looks great, thanks! merging this in

**Pull request merged**
